import "./globals.css";
import SessionAuthProvider from "@/providers/sessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <SessionAuthProvider>
        <body>{children}</body>
      </SessionAuthProvider>
    </html>
  );
}
